//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.ConceptualModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimDate()
        {
            this.FactOrder = new HashSet<FactOrder>();
        }
    
        public int DateKey { get; set; }
        public System.DateTime Date { get; set; }
        public string Datename { get; set; }
        public int Month { get; set; }
        public string Monthname { get; set; }
        public int Quarter { get; set; }
        public string Quartername { get; set; }
        public int Year { get; set; }
        public string Yearname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactOrder> FactOrder { get; set; }
    }
}
