//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.ConceptualModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimProduct()
        {
            this.FactOrderDetails = new HashSet<FactOrderDetails>();
        }
    
        public int ProductKey { get; set; }
        public int ProductId { get; set; }
        public string Productname { get; set; }
        public int CategoryKey { get; set; }
    
        public virtual DimCategory DimCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactOrderDetails> FactOrderDetails { get; set; }
    }
}
