//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.ConceptualModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactOrder()
        {
            this.FactOrderDetails = new HashSet<FactOrderDetails>();
        }
    
        public int OrderNumber { get; set; }
        public int CustomerKey { get; set; }
        public int EmployeeKey { get; set; }
        public int ShipperKey { get; set; }
        public int DateKey { get; set; }
        public int OrdersQuantity { get; set; }
    
        public virtual DimCustomer DimCustomer { get; set; }
        public virtual DimEmployee DimEmployee { get; set; }
        public virtual DimShipper DimShipper { get; set; }
        public virtual DimDate DimDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactOrderDetails> FactOrderDetails { get; set; }
    }
}
