//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.ConceptualModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactOrderDetails
    {
        public int OrderNumber { get; set; }
        public int ProductKey { get; set; }
        public int Quantity { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual FactOrder FactOrder { get; set; }
        public virtual DimProduct DimProduct { get; set; }
    }
}
